__default__:
   time: "72:00:00"
   ntasks: 1
   job-name: default
   hint: nomultithread
   mem: 4G
   partition: mem_0096 
   qos: mem_0096
   output: $(pwd)/log/slurm-%j.out
   error: $(pwd)/log/slurm-%j.err
busco:
   job-name: BUSCO 
orthology:
   job-name: ORTHOLOGY
filter_orthology:
   job-name: FILTORTH
filter_alignments:
   job-name: filtalgn
part_filter_align:
   job-name: FAL
align_trim:
   job-name: alntri
filter_align:
   job-name: FAL
get_filter_statistics:
   job-name: getfilstat 
run_busco:
   job-name: rBUSCO
   mem: 32G
